
package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:

	Logger log = Logger.getLogger(getClass());
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}


scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, BREAK, ENUM, CLASS, ABSTRACT, ELSE, CONST, IF, NEW, PRINT, READ, RETURN, VOID, EXTENDS, CONTINUE, FOR, LEN, SWITCH, CASE;
terminal PLUS, MINUS, STAR, DIV, MOD, EQUAL, LESS, GREATER, COLON, SEMI, COMMA, PERIOD, QMARK, EMARK, APOST, LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK;
terminal AMPER, VLINE, PLUSPLUS, MINUSMINUS, EQUALEQUAL, NOTEQUAL, GREATEREQUAL, LESSEQUAL, AMPERAMPER, VLINEVLINE;
terminal int NUMBER;
terminal String IDENT;

nonterminal VarDeclList, MethodDeclList, VarDecl, MethodDecl;
nonterminal FormPars, StatementList, FormParsList, FormParsDecl, Statement;
nonterminal Expr, Designator, Term, Addop, Factor, ActPars, ActualParamList;

nonterminal rs.etf.pp1.symboltable.concepts.Obj ProgName, Program;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Type;

Program ::= (Program) PROG ProgName:n VarDeclList LBRACE MethodDeclList RBRACE;

ProgName ::= (ProgName) IDENT:progName;

VarDeclList ::= (VarDeclarations) VarDeclList VarDecl
			|
			(NoVarDecl)/* epsilon */
			;
			
VarDecl ::= (VarDecl) Type:varType IDENT:varName SEMI;


Type ::= (Type) IDENT:typeName;

MethodDeclList ::= (MethodDeclarations) MethodDeclList MethodDecl
			|
			(NoMethodDecl)/* epsilon */
			;

MethodDecl ::= (MethodDeclaration) Type:retType IDENT:methName LPAREN FormPars RPAREN VarDeclList LBRACE StatementList RBRACE;

FormPars ::= (FormalParameters) FormParsList
			|
			(NoFormalParameters)/* epsilon */
			;

FormParsList ::= (FormalParameterDeclarations) FormParsList COMMA FormParsDecl
			|
			(SingleFormalParameterDeclaration) FormParsDecl
			;
			
StatementList ::= (Statements) StatementList Statement
			|
			(NoStatement)/*epsilon*/
			;
			
Statement ::= (Assignment) Designator:dest EQUAL Expr:e SEMI
			|
			error SEMI:l
			{: parser.report_error("Izvrsen oporavak do ; u liniji " + lleft, null); :}
			|
			(PrintStatement) PRINT LPAREN Expr RPAREN SEMI
			|
			(ReturnExpr) RETURN Expr SEMI
			|
			(ReturnNoExpr) RETURN SEMI
			;
			
Expr ::=(AddExpr) Expr:te Addop Term:t
	|
	(TermExpr)Term:t
	;

Term ::= (Term) Factor:t;

Factor ::= (FuncCall) Designator LPAREN ActPars RPAREN
		|
		(Var) Designator:d
		|
		(Const) NUMBER
		;
		
ActPars ::= (Actuals) ActualParamList
			|
			(NoActual) /* epsilon */
			;

ActualParamList ::= (ActualParams) ActualParamList COMMA Expr
				|
				(ActualParam) Expr
				;

Designator ::= (Designator) IDENT:name;

Addop ::= (Addop) PLUS;

