
package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;

parser code {:
	
	boolean errorDetected;
	
	Logger log = Logger.getLogger(getClass());
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }


:}


init with {:
	errorDetected = false;
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROG, BREAK, ELSE, CONST, IF, NEW, PRINT, READ, RETURN, VOID, CONTINUE, FOR, LEN, FINDANY, MAP, TRUE, FALSE;
terminal PLUS, MINUS, STAR, DIV, MOD, ARROW, EQUAL, LESS, GREATER, COLON, SEMI, COMMA, PERIOD, QMARK, EMARK, LPAREN, RPAREN, LBRACE, RBRACE, LBRACK, RBRACK;
terminal AMPER, VLINE, PLUSPLUS, MINUSMINUS, EQUALEQUAL, NOTEQUAL, GREATEREQUAL, LESSEQUAL, AMPERAMPER, VLINEVLINE;
terminal int NUMBER;
terminal String IDENT;
terminal char CHARCONST;

nonterminal rs.etf.pp1.symboltable.concepts.Obj ProgName, Program;
nonterminal ProgDeclElemList, ProgDeclElem;

nonterminal ConstDecl, ConstDeclElem, ConstDeclType, ConstDeclElemList;

nonterminal VarDecl, VarDeclElem, LastVarDeclElem, VarDeclElemList, VarDeclList, Elems;

nonterminal MethodDecl, FormParsMethodDecl, MethodDeclList;
nonterminal rs.etf.pp1.symboltable.concepts.Obj TypeMethodDecl;

nonterminal FormPars, FormParsElem, LastFormParsElem, FormParsElemList;

nonterminal Statement, StatementList, ForLoopBegin, ForLoopFirstParam, ForLoopSecondParam, ForLoopThirdParam, IfBlockStart;

nonterminal DesignatorStatementName;
nonterminal rs.etf.pp1.symboltable.concepts.Struct DesignatorStatement;

nonterminal ActPars;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Condition, CondTerm, CondFact;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Expr, NoTernaryExpr, HasTernaryExpr;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Term, TermList;

nonterminal FactorList;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Factor, ActParsFactor,  FactorName;

nonterminal DesignatorName;
nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, DesignatorElemList, DesignatorElem, PeriodElem, ArrayDesignatorName;

nonterminal Assignop, Relop, Addop, Mulop;

nonterminal NumConst, CharConst, BoolConst;

nonterminal rs.etf.pp1.symboltable.concepts.Struct Type, VarDeclType;

precedence left ELSE;







Program ::= (Program) PROG ProgName ProgDeclElemList LBRACE MethodDeclList RBRACE;

ProgName ::= (ProgName) IDENT:name;

ProgDeclElemList ::= (HasProgDeclElemList) ProgDeclElemList ProgDeclElem
					 |
					 (NoProgDeclElemList)/* epsilon */
					 ;

ProgDeclElem ::= (ConstProgDeclElem) ConstDecl
				 |
				 (VarProgDeclElem) VarDecl
				 ;

ConstDecl ::= (ConstDecl) CONST ConstDeclType:type ConstDeclElem ConstDeclElemList SEMI;

ConstDeclType ::= (ConstDeclType) Type:type;

ConstDeclElemList ::= (HasConstDeclElemList) ConstDeclElemList COMMA ConstDeclElem
					  |
					  (NoConstDeclElemList) /* epsilon */
					  ;

ConstDeclElem ::= (NumConstDeclElem) IDENT:name EQUAL NumConst:numConst
				  |
				  (CharConstDeclElem) IDENT:name EQUAL CharConst:charConst
				  |
				  (BoolConstDeclElem) IDENT:name EQUAL BoolConst:boolConst
				  ;


VarDecl ::= (HasVarDecl) VarDeclType:t VarDeclElemList:vdel;

VarDeclType ::= (VarDeclType) Type;

VarDeclElem ::= (BrackVarDeclElem) IDENT:name LBRACK RBRACK COMMA
				|
				(NoBrackVarDeclElem) IDENT:name COMMA
				|
				(ErrorVarDeclElem) error COMMA:l
				{: parser.report_error("Izvrsen VarDecl oporavak do , u liniji " + lleft, null); :}
				;

LastVarDeclElem ::= (BrackLastVarDeclElem) IDENT:name LBRACK RBRACK SEMI
					 |
					 (NoBrackLastVarDeclElem) IDENT:name SEMI
					 |
					 (ErrorLastVarDeclElem) error SEMI:l
					 {: parser.report_error("Izvrsen VarDecl oporavak do ; u liniji " + lleft, null); :}
					 ;

VarDeclElemList ::= (HasVarDeclElemList) VarDeclElem VarDeclElemList
					|
					(LastVarDeclElemList) LastVarDeclElem
					;

VarDeclList ::= (HasVarDeclList) VarDeclList VarDecl
				|
				(NoVarDeclList) /* epsilon */
				|
				error:l SEMI
				{: parser.report_error("Izvrsen VarDeclList oporavak do ; u liniji " + lleft, null); :}
				|
				error:l COMMA
				{: parser.report_error("Izvrsen VarDeclList oporavak do , u liniji " + lleft, null); :}
				;


MethodDecl ::= (MethodDecl) TypeMethodDecl LPAREN FormParsMethodDecl RPAREN VarDeclList LBRACE StatementList RBRACE;

TypeMethodDecl ::= (TMethodDecl) Type IDENT:name
				   |
				   (VMethodDecl) VOID IDENT:name
				   ;
				   

FormParsMethodDecl ::= (HasFormParsMethodDecl) FormPars
					   |
					   (NoFormParsMethodDecl) /* epsilon */
					   ;

MethodDeclList ::= (HasMethodDeclList) MethodDeclList MethodDecl
				   |
				   (NoMethodDeclList) /* epsilon */
				   ;


FormPars ::= (FormPars) FormParsElemList;

FormParsElem ::= (BrackFormParsElem) Type IDENT:name LBRACK RBRACK COMMA
				 |
				 (NoBrackFormParsElem) Type IDENT:name COMMA
				 |
				 (ErrorFormParsElem)error:l COMMA
				 {: parser.report_error("Izvrsen FormParsElem oporavak do , u liniji " + lleft, null); :}
				 ;

LastFormParsElem ::= (BrackLastFormParsElem) Type IDENT:name LBRACK RBRACK
					 |
					 (NoBrackLastFormParsElem) Type IDENT:name
					 |
					 (ErrorLastFormParsElem) error:l
					 {: parser.report_error("Izvrsen LastFormParsElem oporavak do ) u liniji " + lleft, null); :}
					 ;

FormParsElemList ::= (HasFormParsElem) FormParsElem FormParsElemList
					 |
					 (NoFormParsElem) LastFormParsElem
					 ;




Statement ::= (DesignatorStatementStatement) DesignatorStatement SEMI
			  |
			  (IfElseStatement) IfBlockStart Statement ELSE Statement
			  |
			  (IfStatement) IfBlockStart Statement
			  |
			  (BreakStatement) BREAK SEMI
			  |
			  (ContinueStatement) CONTINUE SEMI
			  |
			  (ReturnValueStatement) RETURN Expr SEMI
			  |
			  (ReturnStatement) RETURN SEMI
			  |
			  (ReadStatement) READ LPAREN Designator RPAREN SEMI
			  |
			  (NumConstPrintStatement) PRINT LPAREN Expr COMMA NumConst RPAREN SEMI
			  |
			  (PrintStatement) PRINT LPAREN Expr RPAREN SEMI
			  |
			  (ForStatement) ForLoopBegin ForLoopFirstParam SEMI ForLoopSecondParam SEMI ForLoopThirdParam RPAREN Statement
			  |
			  (StatementListStatement) LBRACE StatementList RBRACE
			  ;

IfBlockStart ::= (HasIfBlockStart) IF LPAREN Condition RPAREN
				 |
				 (ErrorIfBlockStart) IF LPAREN error:l RPAREN
				 {: parser.report_error("Izvrsen IfBlock oporavak do ) u liniji " + lleft, null); :}
				 ;

ForLoopBegin ::= (ForLoopBegin) FOR LPAREN;
ForLoopFirstParam ::= (HasForFirstParam) DesignatorStatement
					   |
					   (NoForFirstParam) /* epsilon */
					   ;

ForLoopSecondParam ::= (HasForSecondParam) Condition
					  |
					  (NoForSecondParam) /* epsilon */
					  ;

ForLoopThirdParam ::= (HasForThirdParam) DesignatorStatement
					   |
					   (NoForThirdParam) /* epsilon */
					   ;

StatementList ::= (HasStatementList) StatementList Statement
				  |
				  (NoStatementList) /* epsilon */
				  ;


DesignatorStatement ::= (AssignopDesignatorStatement) DesignatorStatementName Assignop Expr
						|
						(ActParsDesignatorStatement) DesignatorStatementName LPAREN ActPars RPAREN
						|
						(NoActParsDesignatorStatement) DesignatorStatementName LPAREN RPAREN
						|
						(PlusPlusDesignatorStatement) DesignatorStatementName PLUSPLUS
						|
						(MinusMinusDesignatorStatement) DesignatorStatementName MINUSMINUS
						|
						(ErrorDesignatorStatement) error:l
						{: parser.report_error("Izvrsen DesignatorStatement oporavak do ; u liniji " + lleft, null); :}
						;

DesignatorStatementName ::= (DesignatorStatementName) Designator;

ActPars ::= (MiddleActPars) ActPars COMMA Expr
			|
			(LastActPars) Expr;



Condition ::= (MiddleCondition) Condition VLINEVLINE CondTerm
			  |
			  (LastCondition) CondTerm;

CondTerm ::= (MiddleCondTerm) CondTerm AMPERAMPER CondFact
			 |
			 (LastCondTerm) CondFact;

CondFact ::= (RelopCondFact) NoTernaryExpr Relop NoTernaryExpr
			 |
			 (ExprCondFact) NoTernaryExpr
			 ;



Expr ::= (NoTExpr) NoTernaryExpr
		 |
		 (HasTExpr) HasTernaryExpr
		 ;

HasTernaryExpr ::= (TernaryExpr) Condition QMARK NoTernaryExpr COLON Expr;

NoTernaryExpr ::= (NoTernaryExpr) TermList;

Term ::= (MiddleTerm) Term:t Mulop Factor:f
		 |
		 (LastTerm) Factor:f
		 ;

TermList ::= (HasTermList) TermList Addop Term
			 |
			 (NoTermList) Term
			 |
			 (MinusNoTermList) MINUS Term
			 ;


Factor ::= (DesignatorFactor) Designator:name
		   |
		   (NonEmptyFuncCallFactor) FactorName ActPars RPAREN
		   |
		   (EmptyFuncCallFactor) FactorName RPAREN
		   |
		   (NumFactor) NumConst
		   |
		   (CharFactor) CharConst
		   |
		   (BoolFactor) BoolConst
		   |
		   (NewArrayFactor)NEW Type LBRACK Expr RBRACK
		   |
		   (ExprFactor) LPAREN Expr RPAREN
		   ;


FactorName ::= (FactorName) Designator LPAREN;

Designator ::= (BaseDesignator) IDENT:baseName
			   |
			   (PeriodDesignator) IDENT:baseName PERIOD PeriodElem
			   |
			   (ArrayDesignator) ArrayDesignatorName LBRACK Expr RBRACK
			   ;

ArrayDesignatorName ::= (ArrayDesignatorName) IDENT:baseName;

PeriodElem ::= (LenPeriodElem) LEN
			   |
			   (FindAnyPeriodElem) FINDANY LPAREN Expr RPAREN
			   |
			   (MapPeriodElem) MAP LPAREN IDENT:mapElem ARROW Expr RPAREN
			   ;

Assignop ::= (Assignop) EQUAL;



Relop ::= (RelopEqualEqual) EQUALEQUAL
		  |
		  (RelopNotEqual) NOTEQUAL
		  |
		  (RelopGreater) GREATER
		  |
		  (RelopGreaterEqual) GREATEREQUAL
		  |
		  (RelopLess) LESS
		  |
		  (RelopLessEqual) LESSEQUAL
		  ;


Addop ::= (AddopPlus) PLUS
		  |
		  (AddopMinus) MINUS
		  ;



Mulop ::= (MulopStar) STAR
		  |
		  (MulopDiv) DIV
		  |
		  (MulopMod) MOD
		  ;



Type ::= (Type) IDENT:typeName;


NumConst ::= (NumConst) NUMBER:val;


CharConst ::= (CharConst) CHARCONST:val;


BoolConst ::= (TrueBoolConst) TRUE:val
			  |
			  (FalseBoolConst) FALSE:val
			  ;
			  
